sudo: required

services:
- docker



script:
  - docker build -t terraform-k8s-build .
  - docker run --rm terraform-k8s-build /root/.terraform.d/plugins/terraform-provider-k8s 2>&1 | grep -q "This binary is a plugin"

after_success:
  - test "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" && echo "Pushing to repo" || exit 0
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag terraform-k8s-build $DOCKER_USERNAME/terraform-k8s-build
  - docker push $DOCKER_USERNAME/terraform-k8s-build
