sudo: required

services:
- docker

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t terraform-k8s-build .
    - docker images
    - docker tag terraform-k8s-build $DOCKER_USERNAME/terraform-k8s-build
    - docker push $DOCKER_USERNAME/terraform-k8s-build
